dist: bionic
services: docker
language: bash
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
cache:
  apt: true
  directories:
    - ${HOME}/.local/bin
    - ${HOME}/.local/lib

branches:
  only:
    - master

env:
  matrix:
    - ALPINE_ROS_DISTRO=3.7-kinetic
    - ALPINE_ROS_DISTRO=3.8-melodic
    - ALPINE_ROS_DISTRO=3.11-noetic

before_install:
  - python3 -m pip install --upgrade --user gh-pr-comment
  - BUILD_LINK="[[#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})]"

script:
  - |
    docker run -it --rm \
      -v $(pwd):/src/$(basename $(pwd)):ro \
      -v $(pwd)/log:/logs \
      alpineros/ros-abuild:${ALPINE_ROS_DISTRO}
after_success:
  - |
    gh-pr-comment \
      "${BUILD_LINK} PASSED on ${ALPINE_ROS_DISTRO}" \
      "$(cat ./logs/summary.log || (echo 'Build log not found'; false))"
after_failure:
  - |
    gh-pr-comment \
      "${BUILD_LINK} FAILED on ${ALPINE_ROS_DISTRO}" \
      "$(cat ./logs/summary.log || (echo 'Build log not found'; false))"

jobs:
  include:
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=kinetic
      before_install: python3 -m pip install --upgrade --user gh-pr-comment
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=melodic
      before_install: python3 -m pip install --upgrade --user gh-pr-comment
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=noetic
      before_install: python3 -m pip install --upgrade --user gh-pr-comment
      script: .travis/prerelease_test.sh
