sudo: required
services: docker

cache:
  directories:
    - /home/travis/docker/
env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.lz4
branches:
  only:
    - indigo-devel

before_install:
  - .travis.scripts/load_cache.sh

install: true

script:
  - docker build -t ros-hokuyo3d:latest --pull=true ${TRAVIS_BUILD_DIR}
  - docker run --rm -it -e TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} -e TRAVIS_PULL_REQUEST_SLUG=${TRAVIS_PULL_REQUEST_SLUG} -e TRAVIS_BOT_GITHUB_TOKEN=${TRAVIS_BOT_GITHUB_TOKEN} /catkin_ws/src/hokuyo3d/.travis.scripts/test.sh
  - .travis.scripts/save_cache.sh

